ffw/cart/urls.py
from django.conf.urls import patterns, url
from .views import CartView, OrderView, ThankView, CartSetView, CartRemoveView, CartAddView


urlpatterns = patterns(
    '',
    url(r'^$', CartView.as_view(), name='cart'),
    url(r'^set/$', CartSetView.as_view(), name='cart_set'),
    url(r'^add/$', CartAddView.as_view(), name='cart_add'),
    url(r'^remove/$', CartRemoveView.as_view(), name='cart_remove'),
    url(r'^order/$', OrderView.as_view(), name='order'),
    url(r'^order/thank/$', ThankView.as_view(), name='thank'),
)

ffw/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
admin.autodiscover()


urlpatterns = patterns(
    '',
    # Custom applications
    url(r'^', include('assembly.urls')),
    url(r'^common_pages/', include('common_pages.urls')),
    url(r'^gallery/', include('gallery.urls')),
    url(r'^cart/', include('cart.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^summernote/', include('django_summernote.urls')),
)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += staticfiles_urlpatterns()
    # urlpatterns += patterns(
    #     '',
    #     (r'^%{static_url}/(?P<path>.*)$'.format(static_url=settings.STATIC_URL),
    #         'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
    #     (r'^%{media_url}/(?P<path>.*)$'.format(media_url=settings.MEDIA_URL),
    #         'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    # )

ffw/cart/models.py
# coding: utf-8
from __future__ import unicode_literals

import math
import time

from django.db import models
from django.conf import settings
from django.core.mail import send_mail
from django.utils.translation import ugettext_lazy as _
from model_utils.models import TimeStampedModel

from .exceptions import CartException
from constance import config
from products.models import ProductConfiguration


# TODO: rewrite messages
class Order(TimeStampedModel):
    class Meta:
        verbose_name = _('Order')
        verbose_name_plural = _('Orders')

    name = models.CharField(_('Name'), max_length=255)
    email = models.EmailField(_('E-mail'), max_length=125, blank=True)
    phone = models.CharField(_('Phone'), max_length=125)
    contacts = models.TextField(_('Additional contacts'), blank=True)
    total = models.DecimalField(_('Total'), decimal_places=2, max_digits=9, default=0)
    count = models.IntegerField(_('Quantity'), default=0)
    is_resolved = models.BooleanField(_('Is order resolved'), default=False)

    def __str__(self):
        return 'order #{}'.format(self.id)

    def _get_user_message(self):
        return (
            "Успешно оформлен заказ на сайте ffw. Номер заказа {}. Cумма заказа {} грн.\n\n"
            "Детали заказа:\n"
            "{}\n\n"
            "Наши контакты:\n"
            "(044) 510-91-03\n"
            "(067) 417-00-21\n"
            "(050) 520-00-21\n"
            "Email: info@waterproff.ua\n"
        ).format(
            self.pk,
            self.total,
            '\n'.join([p.to_representaion() for p in self.products.all()]),
        )

    def _get_admin_message(self):
        return (
            "Получен новый заказ на сайте ffw. На сумму {} грн.\n\n"
            "Детали заказа:\n"
            "{}\n\n"
            "Контакты заказчика:\n"
            "Имя: {}\n"
            "Email: {}\n"
            "Телефон: {}\n"
            "Другие контакты: {}\n"
        ).format(
            self.total,
            '\n'.join([p.to_representaion() for p in self.products.all()]),
            self.name,
            self.email,
            self.phone,
            self.contacts
        )

    # TODO: Make this call async.
    def send_customer_email(self):
        if self.email:
            send_mail(
                'Успешно оформлен заказ на сайте ffw. Номер заказа: {}'.format(self.id),
                self._get_user_message(),
                settings.EMAIL_HOST_USER,
                [self.email],
            )
        # if self.email:
        #     thr = threading.Thread(
        #         target=send_mail,
        #         args=(
        #             'Успешно оформлен заказ на сайте ffw. Номер заказа: {}'.format(self.id),
        #             self._get_user_message(),
        #             settings.EMAIL_HOST_USER,
        #             [self.email],
        #         ),
        #         kwargs={
        #             'fail_silently': True
        #         },
        #     )
        #     thr.start()
        # return thr

    def send_admin_email(self):
        send_mail(
            'Новый заказ на сайте ffw. Номер заказа: {}'.format(self.id),
            self._get_admin_message(),
            settings.EMAIL_HOST_USER,
            [email.strip() for email in config.ADMIN_EMAILS.split(',')],
        )
        # thr = threading.Thread(
        #     target=send_mail,
        #     args=(

        #     ),
        #     kwargs={
        #         'fail_silently': True
        #     },
        # )
        # thr.start()
        # return thr


class OrderedProduct(models.Model):
    class Meta:
        verbose_name = _('Ordered products')
        verbose_name_plural = _('Ordered products')

    order = models.ForeignKey(Order, verbose_name='Order', related_name='products')
    # XXX: This FK provides circular dependency in applications cart and products. We need to use abstract product
    # from cart settings. Also FK should be nullable
    product = models.ForeignKey(ProductConfiguration, verbose_name='Product', related_name='ordered_product')
    name = models.CharField(_('Name'), max_length=127)
    code = models.CharField(_('Code'), max_length=127)
    price = models.DecimalField(_('Price'), decimal_places=2, max_digits=7)
    quant = models.IntegerField(_('Quantity'), default=0)
    total = models.DecimalField(_('Total'), decimal_places=2, max_digits=9)

    def __str__(self):
        return u'Product with id: {}'.format(self.product.id)

    def to_representaion(self):
        return ' - {} ({}): количество: {}, сумма {}, (цена за единицу продукта {});'.format(
            self.name, self.code, self.quant, self.total, self.price)


class CartProduct(object):
    """ Wrapper for abstract product that is defined by cart application settings """
    # TODO: rewrite this class to use product table configuration from cart settings
    def __init__(self, product_pk):
        product_pk = int(product_pk)

        try:
            self.product = ProductConfiguration.objects.get(pk=product_pk)
        except ProductConfiguration.DoesNotExist:
            raise CartException("Can not find product with pk {}".format(product_pk))

    @property
    def name(self):
        return self.product.product.name

    @property
    def code(self):
        return self.product.code

    @property
    def price(self):
        return self.product.price_uah

    @property
    def pk_int(self):
        return self.product.pk

    @property
    def pk_str(self):
        return str(self.product.pk)


class Cart(object):

    def __init__(self, cart):
        self.cart = cart

    def _calculate(self):
        """ Recalculate product quantity and sum """
        self.cart['total'] = sum([v['sum_'] for v in self.cart['products'].values()])
        self.cart['count'] = sum([v['quant'] for v in self.cart['products'].values()])
        self.cart['ordered_products'] = sorted(self.cart['products'].values(), key=lambda x: x['added'], reverse=True)

    def set(self, product_pk, quant):
        if quant > 0:
            product = CartProduct(product_pk)

            frac, whole = math.modf(float(product.price))
            converter = float if frac else int

            self.cart['products'][product_pk] = {
                'pk': product_pk,
                'name': product.name,
                'product_code': product.code,
                'price': converter(product.price),
                'code': product.code,
                'quant': quant,
                'sum_': converter(quant * product.price),
                'added': time.time(),
            }
            self._calculate()
        else:
            self.remove(product_pk)

    def remove(self, product_pk):
        product = CartProduct(product_pk)
        try:
            del self.cart['products'][product.pk_str]
        except KeyError:
            raise CartException('Cart does not contain product with key {}'.format(product.pk_str))
        self._calculate()

    def add(self, product_pk, quant):
        product = CartProduct(product_pk)

        if product.pk_str in self.cart['products'].keys():
            self.cart['products'][product.pk_str]['quant'] += quant
            self.cart['products'][product.pk_str]['sum_'] = float(
                self.cart['products'][product.pk_str]['quant'] * product.price)
        else:
            self.set(product_pk, quant)

        self._calculate()

ffw/cart/forms.py
# coding: utf-8
from django.forms import ModelForm, Textarea

from models import Order


class OrderForm(ModelForm):
    class Meta:
        model = Order
        fields = ('name', 'email', 'phone', 'contacts')
        widgets = {
            'contacts': Textarea(attrs={'cols': 40, 'rows': 2}),
        }

ffw/cart/views.py
#  -*- coding: utf-8 -*-
import json

from django.contrib import messages
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from django.utils.translation import ugettext_lazy as _
from django.views.generic import View, TemplateView, FormView

from .forms import OrderForm
from .models import Cart, OrderedProduct
from products.models import ProductConfiguration


# XXX: Cart endpoints completely breaks REST architecture. We need to rewrite them.
class CartMixin(object):

    def dispatch(self, request, *args, **kwargs):
        self.cart = request.session.get('cart', {'products': {}, 'total': 0, 'count': 0})
        return super(CartMixin, self).dispatch(request, *args, **kwargs)

    def format_response(self, request):
        request.session['cart'] = self.cart
        return HttpResponse(json.dumps({'cart': request.session['cart']}))


class CartView(CartMixin, View):

    def get(self, request, *args, **kwargs):
        if request.is_ajax:
            return self.format_response(request)

    def post(self, request, *args, **kwargs):
        """ Clear cart """
        if request.is_ajax:
            self.cart = {'products': {}, 'total': 0, 'count': 0}
            return self.format_response(request)


class CartRemoveView(CartMixin, View):

    def post(self, request, *args, **kwargs):
        if request.is_ajax:
            product_pk_list = json.loads(request.POST.get('product_pk_list', '[]'))
            for product_pk in product_pk_list:
                Cart(self.cart).remove(product_pk)
            return self.format_response(request)


class CartSetView(CartMixin, View):

    def _call_cart(self, product_pk, quant):
        Cart(self.cart).set(product_pk, quant)

    def post(self, request, *args, **kwargs):
        if request.is_ajax():
            product_dict = json.loads(request.POST.get('product_dict', '{}'))

            for pk, quantity in product_dict.items():
                self._call_cart(product_pk=pk, quant=int(quantity))
            return self.format_response(request)


class CartAddView(CartSetView):
    def _call_cart(self, product_pk, quant):
        Cart(self.cart).add(product_pk, quant)


class OrderView(FormView):
    template_name = 'order.html'
    form_class = OrderForm

    def get_success_url(self):
        return reverse('home')

    def form_valid(self, form):
        order = form.save()
        self.count = 0
        self.total = 0

        for key, value in self.request.session['cart']['products'].items():
            product = ProductConfiguration.objects.get(id=int(key))
            ordered_product = OrderedProduct(
                order=order,
                product=product,
                name=product.product.name,
                code=product.code,
                price=product.price_uah,
                quant=value['quant'],
                total=round(product.price_uah * value['quant'], 2))
            ordered_product.save()
            self.total += ordered_product.total
            self.count += ordered_product.quant

        order.count = self.count
        order.total = self.total
        order.save()

        order.send_customer_email()
        order.send_admin_email()
        self.request.session['cart'] = {'products': {}, 'total': 0, 'count': 0}
        messages.info(self.request, _('Order was successfully created. Our manager will contact you during the day.'))
        return super(OrderView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(OrderView, self).get_context_data(**kwargs)
        context['is_cart_page'] = True
        return context


class ThankView(TemplateView):
    template_name = 'thank.html'

ffw/cart/templates/cart.html
<!--For test only-->

{% load staticfiles %}
{% load i18n %}



<!DOCTYPE html>
<html lang="ru-RU">
<head>
</head>
<body>

<div id='cart'   data-url="{% url 'cart' %}"></div>
<span> {{cart}}</span><br>
<button id='session'>Смотреть корзину в сессии</button>  



</body>
</html>

ffw/cart/templates/order.html
{% extends 'base.html' %}

{% load staticfiles %}
{% load i18n %}


{% block content %}
<!-- product -->
<section class="product">
    <div class="wrap">
        <!-- breadcrumps -->
        <div class="breadcrumps">
            <ul>
                <li><a href="/">Главная страница</a></li>
                <li><span>Корзина и оформление заказа</span></li>
            </ul>
        </div>
        <!-- /breadcrumps -->
        <div class="products-in-view cart-order-page">
            <div class="product-blocks">
                <!-- product-block -->
                <div class="product-block" id="display-cart">
                    <h3 class="product-block-title">
                        Корзина
                    </h3>
                    <div class="product-block-content">
                        <table class="combain-product-list">
                            <tr>
                                <th>Товар</th>
                                <th>Количество</th>
                                <th>Цена</th>
                                <th></th>
                            </tr>
                            <!-- item -->
                            {% for key, value in request.session.cart.products.items %}
                                <tr data-role={{ key }}>
                                    <td>
                                        <span class="name">{{ value.name }} ({{ value.code }})</span>
                                    </td>
                                    <td>
                                        <div data-front="price-input">
                                            <span data-front="cart-input-count-minus">
                                                <i class="fa fa-minus-circle"></i>
                                            </span>
                                            <input class="count" type="number" value="{{ value.quant }}" min="1"
                                                data-front="price-input-count"
                                                data-product-id="{{ key }}" data-role='quant'  data-pk= {{ key }} value={{ value.quant }}>
                                            <span data-front="cart-input-count-plus">
                                                <i class="fa fa-plus-circle"></i>
                                            </span>
                                        </div>
                                    </td>
                                    <td>
                                        <div class="price-line">
                                            <span class="price" data-role={{key}}_sum>{{value.sum_}}</span>
                                            <span class="currency">грн.</span>
                                        </div>
                                    </td>
                                    <td>
                                        <span data-front="cart-input-count-delete">
                                            <i class="fa fa-times-circle" data-role='remove' data-value='{{ key }}'></i>
                                        </span>
                                    </td>
                                </tr>
                            {% endfor %}
                            <!-- /item -->
                        </table>
                        <!-- combain-product-summary -->
                        <div class="combain-product-summary">
                            Заказано товаров <span data-role="cart-count">{{ cart.count }}</span> на сумму <span data-role="cart-total">{{ cart.total }}</span> грн.
                        </div>
                        <!-- /combain-product-summary -->
                    </div>
                </div>
                <!-- /product-block -->
                <!-- product-block -->
                <div class="product-block" id="order-cart" data-role="order-block">
                    <h3 class="product-block-title">
                        Оформить заказ
                    </h3>
                    <form action='.' method='post' data-role='order-form'>{% csrf_token %}
                        <div class="order-form">
                            <div class="step-1 active" data-role="order-step-1">
                                <fieldset>
                                    <label>Имя:</label>
                                    <div class="input">
                                        <input id='id_name' name='name' type="text" required>
                                    </div>
                                </fieldset>
                                <fieldset>
                                    <label>Телефон:</label>
                                    <div class="input">
                                        <input id="id_phone" name="phone" type="tel" data-role="phone-mask" required>
                                    </div>
                                </fieldset>
                                <fieldset>
                                    <label>Email:</label>
                                    <div class="input">
                                        <input id="id_email" type="email" name="email">
                                    </div>
                                </fieldset>
                                <fieldset>
                                    <label>Дополнительная информация:</label>
                                    <div class="input">
                                        <textarea id="id_contacts" name="contacts"></textarea>
                                    </div>
                                </fieldset>
                                <fieldset class="order-button">
                                    <button type="submit" class="button button-blue">Оформить заказ</button>
                                </fieldset>
                            </div>
                        </div>
                    </form>
                </div>
                <!-- /product-block -->
            </div>
        </div>
    </div>
</section>

{% endblock content %}

{% block js %}
    <script src="{% static 'cart/cart.js' %}"> </script>
{% endblock js %}

ffw/cart/templates/thank.html
<!--For test only-->

{% load staticfiles %}
{% load i18n %}



<!DOCTYPE html>
<html lang="ru-RU">
<head>
</head>
<body>

<div id='cart'   data-url="{% url 'cart' %}"></div>
<span> Ваш заказ успешно оформлен! </span><br>
<a href="/"> Вернуться на сайт</a>



</body>
</html>